#!/bin/bash
#
# chkconfig: 345 99 01
# description: docker-sandbox

. /etc/init.d/functions

name="docker-sandbox"
parent_dir="/vagrant"
prog="node $parent_dir/lib >> /var/log/$name 2>&1 &"
lockfile="/var/lock/subsys/$name"
pidfile="/var/run/${name}.pid"
user="vagrant"

start() {
  echo -n "Starting $name: "
  daemon --pidfile $pidfile --user $user $prog
  local retval=$?
  [ $retval -eq 0 ] && touch $lockfile
  return $retval
}

stop() {
  echo -n "Shutting down $name: "
  killproc $prog
  local retval=$?
  [ $retval -eq 0 ] && rm -f $lockfile
  return $retval
}

case "$1" in
  start) start ;;
  stop) stop ;;
  status) status $prog ;;
  restart) stop; start ;;
  *) echo "Usage: $name {start|stop|status|restart"; exit 1 ;;
esac
exit $?
